# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79375e73ea903a99f357dc70260a39f100e8031f70c92e64ce809fe28bef2ce9798117b3898715e758c77834768131a900c919291c37027785b55208c233fef

test:
  secret_key_base: 048002d173c675497e69836e25fe95e622e97eba2e3c2955aa9d92da2aa5b5d7f4c969845e5020898d9aaebcf14c66435bd215b747fd21b04f9dfbef8f71becf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
